### ISSUE TITLE
The mod disables other mods flight abilities when in mod-packs.

### ISSUE THREAD

**Issue by Zer0Lyfe** [Ephys/minecraft-magic-feather#5]
It disables all forms of flight from other mods as your code blocks other mods code to work. Examples of this is shown in this reddit post:
https://www.reddit.com/r/feedthebeast/comments/84rcy8/magic_feather_disabling_all_other_forms_of/
this code here disable all other mods abilities flight abilities:
https://github.com/Ephys/minecraft-magic-feather/blob/master/src/main/java/be/ephys/magicfeather/ItemMagicFeather.java

**Comment by ephys** [comment]
That's definitely not intended, will fix!

**Comment by Zer0Lyfe** [comment]
thank you ephys :D

**Comment by stevenkxu** [comment]
Hey, just a suggestion for how to make this work if you haven't come up with your own solution for it:

Why not give the player a "flight" potion effect when they both have the magic feather in their inventory and are in range of a beacon? Then, instead of stripping away their flight when they move out of range, you can just have the potion effect expire naturally.

Of course, if you already have your own solution, you can just disregard this suggestion.

**Comment by MissPotato** [comment]
Any luck with fixing this?

**Comment by Dimentive** [comment]
@Ephys What’s your progress on the fix?

This mod looks amazing, but I don’t want to use it until this has been fixed, as it’s a pretty major bug.

**Comment by Fortist** [comment]
It's been a year, it's dead Jim

**Comment by Dimentive** [comment]
Looks like it. That’s a shame, though.
I hope someone will fork this and take over the project. It’s such a nifty mod!

**Comment by ephys** [comment]
(I'm back)

So as suspected it was caused by the slow-fall feature (you don't get fall damage until you hit the ground when stripped of flight)

I've reworked the code so that the mod will only strip you of creative flight once and only if it granted it first

**Comment by Dimentive** [comment]
@Ephys **Sweet!** When is the update being released, and will it be for 1.12.2?

**Comment by ephys** [comment]
@Dimentive I'll be testing the changes I made for #4 after work, then I'll test the mod in an actual modpack before I release it. If everything goes smoothly it should be out in a few hours

And yes, 1.12.2 :) 1.15 soon™️

**Comment by Dimentive** [comment]
Sweet! As soon as it’s released, I’m adding it to my modpack!

**Comment by ephys** [comment]
It's under review by curse but should be available shortly :)

https://www.curseforge.com/minecraft/mc-mods/magic-feather/files/all

Edit: already approved

**Comment by Dimentive** [comment]
I genuinely, honest to god love you. I don’t believe in god, though, so that doesn’t hold much weight, but I still love you.

I thought this mod was abandoned forever, but then you show up out of nowhere and resurrect it like you’re a necromancer. Not even joking when I say I’ve been waiting for this. This is the perfectly balanced flight item. It’s a great mid-step between basic flight like the ring of the flying squid, jetpacks, and other simple flight items and full creative flight. I love this mod so much and hope it works as advertised! I’ll install it immediately.

**Comment by ephys** [comment]
hearing that makes me super happy! Enjoy :)
